# .circleci/config.yml

version: 2.1
orbs: 
  macos: circleci/macos@2.0.1
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm cache verify
      - run: npm install
      - run: npm test
      - run: npm run lint
workflows:
  version: 2.1
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - develop