# .circleci/config.yml

version: 2.1
orbs: 
  node: circleci/node@5.0.0
jobs:
  test:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - run: npm cache verify
      - run: npm install
      - run: npm test
      - run: npm run lint
workflows:
  version: 2.1
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - develop